apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: nawat1/microservices:auth-image
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: mongo-auth
            - name: DB_PORT
              value: "27017"
