apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-auth
spec:
  serviceName: "mongo-auth"
  replicas: 1
  selector:
    matchLabels:
      app: mongo-auth
  template:
    metadata:
      labels:
        app: mongo-auth
    spec:
      containers:
        - name: mongo-auth
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-auth-storage
              mountPath: /data/db

  volumeClaimTemplates:
    - metadata:
        name: mongo-auth-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
