apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-product
spec:
  serviceName: "mongo-product"
  replicas: 1
  selector:
    matchLabels:
      app: mongo-product
  template:
    metadata:
      labels:
        app: mongo-product
    spec:
      containers:
        - name: mongo-product
          image: mongo:latest
          ports:
            - containerPort: 27018
          volumeMounts:
            - name: mongo-product-storage
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-product-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-product
spec:
  selector:
    app: mongo-product
  ports:
    - protocol: TCP
      port: 27018
      targetPort: 27017
  type: ClusterIP
