apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: slk34/microservices:product-image
          ports:
            - containerPort: 3001
          env:
            - name: DB_HOST
              value: mongo-product
            - name: DB_PORT
              value: "27018"
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-dep
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: ClusterIP
