version: "3"
services:
  mongo-auth:
    image: mongo:latest
    volumes:
      - mongo-auth-data:/data/db
    ports:
      - "27017:27017"

  mongo-catalog:
    image: mongo:latest
    volumes:
      - mongo-catalog-data:/data/db
    ports:
      - "27018:27017"

  mongo-cart:
    image: mongo:latest
    volumes:
      - mongo-cart-data:/data/db
    ports:
      - "27019:27017"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    networks:
      - elasticnet
  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.1
    ports:
      - "5601:5601"
    networks:
      - elasticnet
    depends_on:
      - elasticsearch

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - elasticnet

volumes:
  esdata1:
    driver: local
  mongo-auth-data:
  mongo-catalog-data:
  mongo-cart-data:
  rabbitmq-data:

networks:
  elasticnet:
    driver: bridge
